### ISSUE TITLE
singleLocation don't ask for permission

### ISSUE THREAD

**Issue by m-ruhl** [AckeeCZ/ReactiveLocation#27]
Hey 👋 ,

I did use ReactiveLocation 3.1.1 before, and currently try to move to the `master` because of the Dependency to ReactiveSwift 6.

Previously we trigger the permission-request when the `location-button` of our app was clicked. As with the new version, you cannot explicitly ask for the permission, my approach was to retrieve a `singleLocation`, but apparently this does not tigger a permission request?

**Comment by olejnjak** [comment]
Hi @m-ruhl, 

sorry for such long response time 😔 by some mistake noone had this repo in his watch list, we'll look into it but at first sight it seems like a bug, that might also be the reason why no version is released 🙂

**Comment by LukasHromadnik** [comment]
This issue should be resolved by #29.
