### ISSUE TITLE
How to switch between result?

### ISSUE THREAD

**Issue by O-mkar** [AckeeCZ/ReactiveLocation#4]
Can you give me a example to switch between results?

**Comment by olejnjak** [comment]
Hello,

the https://github.com/antitypical/Result is generic `enum` with types of `Value` and `Error` which specify associated values with its cases (`Success`/`Failure`). This means you can switch over this `Result` using `switch`.

The example would look like this:

```
struct Error: ErrorType {}
let signal = SignalProducer<String,Error>(error: Error())

signal.startWithResult { result in
    switch result {
    case .Success(let s): // signal has sent .Next event with value of s
        print(s)
    case .Failure(let error): // signal has sent error (.Failed event)
        print(error)
    }
}
```

**Comment by olejnjak** [comment]
@O-mkar Clear for now? :-)
