### ISSUE TITLE
new release from master

### ISSUE THREAD

**Issue by lukaszspaczynski** [AckeeCZ/ReactiveLocation#9]
Hi, I saw that you have migrated to latest ReactiveSwift on master, could you also prepare release? Theres no way to use branch name in podspec dependency section - only version number, and the latest 2.0.1 didn't contain migrated code.

**Comment by ackdom** [comment]
Hi,


I just release version 2.0.2 

🎉  Congrats

 🚀  ReactiveLocation (2.0.2) successfully published
 📅  January 18th, 14:37
 🌎  https://cocoapods.org/pods/ReactiveLocation
 👍  Tell your friends!

cheers
